### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by shishir9747** [XG-2580/Lavalink#1]
When I run any Filter command, it show the embed but noting change in music

**Comment by XG-2580** [comment]
You can show me the error on the terminal of bot. To make me easy to solve it for you.

**Comment by shishir9747** [comment]
![Screenshot 2021-11-10 105310](https://user-images.githubusercontent.com/39312279/141052138-2dc2ed86-220b-461e-9859-bc40389de0dc.png)
its not working on my vps. But when I host lava player on windows. it work fine

**Comment by XG-2580** [comment]
I see, It think what vps are you using?

**Comment by shishir9747** [comment]
I am using vps from contabo. 
os: ubuntu 20.04 
java version "17"

maybe its a problem of lavaplayer. I downloaded it from another project as you didn't add this in this project
